image: alpine:latest

variables:
  HTTP_PROXY: ${HTTP_PROXY}
  HTTPS_PROXY: ${HTTPS_PROXY}
  NO_PROXY: ${NO_PROXY}

stages:
  - test
  - docker_image
  - publish_to_test
  - review
  - stage
  - stop
  - production

package_and_tests:
  stage: test
  image: $CI_PROD_REGISTRY/ci/alpine-jdk-maven:1.0.0
  script:
    - mvn package
  artifacts:
    paths: ["target/*.jar", "target/Dockerfile", "target/entrypoint.sh"]
  only:
    refs:
      - branches
  except:
    refs:
      - tags

docker_image:
  image: $CI_TOOLS_IMAGE
  stage: docker_image
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: $CI_PROD_REGISTRY/ci/dind:1.0.0
  script:
    - setup_docker
    - cd target
    - build
  only:
    - branches
  except:
    refs:
      - master
      - tags

docker_prod_image:
  image: $CI_TOOLS_IMAGE
  stage: docker_image
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: $CI_PROD_REGISTRY/ci/dind:1.0.0
  script:
    - setup_docker
    - cd target
    - build
  only:
    - master
  except:
    refs:
      - tags


review_test_env:
  stage: review
  image: $CI_TOOLS_IMAGE
  script:
    - configure_helm
    - deploy_test_chart name=${CI_ENVIRONMENT_SLUG}-tst-env "test"
    - test_app_deploy
    - echo "How to connect to database: "
    - echo "kubectl exec -it -n ${KUBE_NAMESPACE} ${TEST_CHART_POD_NAME} -- mysql whoisdb <<< show tables;"

  environment:
    name: $CI_COMMIT_REF_NAME
    url: $CI_ENVIRONMENT_SLUG.${CI_PROJECT_NAME}.tst.xyz.apnic.net
    on_stop: stop_environment
  only:
    refs:
      - branches
  except:
    refs:
      - tags
      - master
    variables:
      - $DISABLED_REVIEW

review_prod_env:
  stage: review
  image: $CI_TOOLS_IMAGE
  script:
    - configure_helm
    - staging_app_deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: ${CI_PROJECT_NAME}.tst.xyz.apnic.net
    on_stop: stop_environment
  only:
    refs:
      - master
  except:
    refs:
      - tags
    variables:
      - $DISABLED_REVIEW

publish_chart_to_test_repo:
  stage: test
  image: $CI_TOOLS_IMAGE
  script:
    - publish_chart tst
  only:
    refs:
      - branches
  except:
    refs:
    - tags
    variables:
    - $DISABLED_PUBLISH

publish_chart_to_prod_repo:
  stage: production
  image: $CI_TOOLS_IMAGE
  script:
    - publish_chart prod
  only:
    refs:
      - master
  except:
      variables:
        - $DISABLED_PUBLISH

git_tag:
  stage: production
  image: $CI_TOOLS_IMAGE
  script:
    - git_tag ci_tests
  only:
    refs:
      - master
  except:
      variables:
        - $DISABLED_PUBLISH

stop_environment:
  stage: stop
  image: $CI_TOOLS_IMAGE
  allow_failure: false
  variables:
    GIT_STRATEGY: none
  script:
    - clear_test_environment
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    refs:
      - branches
  except:
    refs:
      - tags
    variables:
      - $DISABLED_STOP_ENV

# ---------------------------------------------------------------------------

.auto_devops: &auto_devops |
  [[ "$TRACE" ]] && set -x
  [[ "$DEBUG_SLEEP" ]] && sleep $DEBUG_SLEEP
  source /ci-utils.sh || true

before_script:
  - *auto_devops
