apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rdapd
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  ports:
    - name: http-rdap
      protocol: TCP
      port: 8080
      targetPort: http-rdap
