
# Settings to specifically control the RDAP protocol used by this application.
rdap:

  # A list of default notices that get appended to each RDAP response from this
  # server. Notice objects take the following structure.
  # title: # Title of the notice
  # description: # List of string describing the notice
  # links: # List of link objects in the folloing form.
  #   - href: # href value as per RDAP spec
  #     rel: #ref value as per RDAP spec
  #     type: #type of link
  notices: []

  # Port43 value for RDAP responses
  port43: null

  # Enables history endpoints (https://github.com/APNIC-net/rdap-history).
  # If this setting is omitted, history endpoints will be active.
  historyEndpointsEnabled: true

database:
  host: localhost
  database: rdapd
  username: root
  password: null

spring:
  application:
    name: @project.artifactId@

  datasource:
    url: "jdbc:mysql://${database.host}:3306/${database.database}?useunicode=true&characterencoding=utf8&charactersetresults=utf8&useSSL=false"
    username: "${database.username}"
    password: "${database.password}"

# Configuration for loading data from RPSL dump files.
# Notice that you need to activate the "rpsl-data" spring profile to enable loading from RPSL data.
#rpslData:
  # FTP URI for the RPSL dump file.
  # E.g.: "ftp://user:password@ftp.apnic.net/pub/incoming/krnic/krnic.db.tar.gz"
  # Cron expression for loading RPSL data (Spring format - i.e. includes seconds).
  #updateCronExpr: 0 0 * * * *

management:
  port: 8081

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
