{{- if .Values.ingress.enabled -}}
{{- $fullName := include "application.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ template "application.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    apnic.net/team: pt-registry
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if kindIs "slice" .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{ end }}
      {{- $defaultSecretName :=  (print $fullName "-tls") -}}
      secretName: {{ default $defaultSecretName .secretName }}
  {{- end }}
{{- else if kindIs "map" .Values.ingress.tls }}
  tls:
    - hosts:
      {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }}
      {{ end }}
      {{- $defaultSecretName :=  (print $fullName "-tls") -}}
      secretName: {{ default $defaultSecretName .Values.ingress.tls.secretName }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
  {{- if $ingressPaths }}
	{{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
	{{- end }}
  {{- else }}
          - backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
  {{- end }}
{{- end }}
