{{- if .Values.loaderOutdatedPrometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-operator
    role: alert-rules
  name: rdapd-loader-outdated-{{ .Release.Name }}
spec:
  groups:
    - name: registry
      rules:
        - alert: RdapdLoaderOutdated-{{ .Release.Name }}
          annotations:
            message: {{ .Values.loaderOutdatedPrometheusRule.message }}
            description: {{ .Values.loaderOutdatedPrometheusRule.description }}
          expr: rdapd_loader_status{app_kubernetes_io_instance={{ .Release.Name | quote }}}==1
          labels:
            {{- toYaml .Values.loaderOutdatedPrometheusRule.labels | nindent 12 }}
{{- end }}