{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "application.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    apnic.net/team: pt-registry
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "application.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
