apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rdapd
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "application.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  rdapd-whoisdb-username: {{ .Values.rdapd.whoisDB.username | b64enc | quote }}
  rdapd-whoisdb-password: {{ .Values.rdapd.whoisDB.password| b64enc | quote }}
