{{- if and .Values.rdapd.whoisDB.username .Values.rdapd.whoisDB.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "application.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    apnic.net/team: pt-registry
type: Opaque
data:
  rdapd-whoisdb-username: {{ .Values.rdapd.whoisDB.username | toString | b64enc | quote }}
  rdapd-whoisdb-password: {{ .Values.rdapd.whoisDB.password | toString | b64enc | quote }}
{{- end }}
