apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rdapd
  labels:
    chart: {{ template "application.chart" . }}
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "fullname" . }}
    chart: {{ template "application.chart" . }}
  ports:
    - name: http-rdap
      protocol: TCP
      port: 8080
      targetPort: http-rdap
  type: {{ .Values.service.type }}
