# This file overrides values from the application chart
# (<project-root>/chart/values.yaml) for the purpose of
# setting up a testing instance.

rdapd:
  whoisDB:
    # Because we are using a domain/namespace agnostic service the host
    # is not fully qualified. We rely on Kubernetes DNS search path.
    host: 10.0.0.24
    db: apnicdb
    username: software
    password: test1234

service:
  type: NodePort
  port: 8080
ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
      certmanager.k8s.io/cluster-issuer: kluster
    hosts:
      - rdapd.tst.xyz.apnic.net
    enabled: true
resources:
  requests:
    memory: "1024Mi"
    cpu: "250m"
  limits:
    memory: "4096Mi"
    cpu: "500m"
